site:
  title: Antora Docs
  start_page: component-b::index.adoc 
content:
  sources: 
  - url: https://github.com/Persival-GmbH/asciidoc-test.git
    branches: HEAD
  - url: https://github.com/Persival-GmbH/asciidoc-test.git
    branches: [main]
    start_path: doc
ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
